### PR TITLE
Refactor loopback2 to reduce code duplication.

### PR DESCRIPTION
**Pull request by djpetti**
Now integration tests which rely upon loopback2 can use the
exact same mechanisms to read the config file data.

NOTE: This PR goes with the one for the equivalently-named branch in node. Ideally, they should be merged at the same time, otherwise stuff will probably break.

### CODE REVIEW

**Comment by c00w** [comment]
I'll look at this tomorrow. Why will they break though?

**Comment by c00w** [comment]
Ah because you moved the binary. It's likely possible to just put the library inside of a sub directory, as opposed to the binary. The autoroute/node directory is a little special.

**Comment by c00w** [comment]
Also there doesn't seem to be a need for this binary to exist anymore. Can we just turn it into a utility library (inside integration_tests in autoroute/node?) which is used directly from the network_sim_test.go and delete this whole repo?

**Comment by c00w** [comment]
AKA I don't see a reason to do this out of process.

**Comment by djpetti** [comment]
Yeah, I was modeling my structure after node. Interesting idea. I suppose we can fuse this into node. Inter-repo dependencies are really annoying anyway...

**Comment by djpetti** [comment]
It looks like all loopback2 code is moving permanently into the node repository, so I am closing this PR.

**Pull request closed without merging**
